#!/usr/bin/env python3
"""
AI Education Assistant Agent - Main Entry Point

A multi-agent system for personalized C++ and algorithms exam preparation.
Capstone Project for Google AI Agents Intensive Course (Agents for Good Track - Education)

Author: dk7-7
Date: November 2025
"""

import os
import logging
from typing import Dict, List, Optional
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('education_agent.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class EducationAssistantAgent:
    """
    Main coordinator agent that orchestrates the multi-agent system.
    
    This demonstrates:
    - Multi-agent system with sequential coordination
    - Custom tools integration
    - Session management and memory
    - Context engineering
    - Observability with logging
    """
    
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize the Education Assistant Agent.
        
        Args:
            api_key: Google API key for Gemini (defaults to env variable)
        """
        self.api_key = api_key or os.getenv('GOOGLE_API_KEY')
        if not self.api_key:
            raise ValueError("GOOGLE_API_KEY not found in environment")
        
        # Initialize agents
        logger.info("Initializing Education Assistant Agent...")
        self.coordinator = None  # CoordinatorAgent
        self.content_generator = None  # ContentGeneratorAgent  
        self.quiz_agent = None  # QuizAgent
        
        # Initialize tools
        self.tools = {
            'cpp_executor': None,  # CPPCodeExecutor
            'concept_search': None,  # ConceptSearchTool
            'progress_tracker': None  # ProgressTracker
        }
        
        # Session management
        self.sessions = {}  # InMemorySessionService
        self.current_session_id = None
        
        logger.info("Agent initialization complete")
    
    def explain_concept(self, topic: str, difficulty: str = "medium") -> str:
        """
        Explain a C++ or algorithm concept with examples.
        
        Args:
            topic: Topic to explain (e.g., "quicksort", "heaps")
            difficulty: Difficulty level (easy/medium/hard)
            
        Returns:
            Detailed explanation with code examples
        """
        logger.info(f"Explaining concept: {topic} (difficulty: {difficulty})")
        
        # This would call the ContentGeneratorAgent
        explanation = f"""
        ## {topic.title()}
        
        [Concept explanation would be generated here by ContentGeneratorAgent]
        
        ### C++ Implementation:
        ```cpp
        // Sample code for {topic}
        // Generated by AI agent
        ```
        
        ### Complexity:
        - Time: O(n log n)
        - Space: O(n)
        """
        
        return explanation
    
    def generate_quiz(self, topics: List[str], num_questions: int = 5) -> Dict:
        """
        Generate a quiz on specified topics.
        
        Args:
            topics: List of topics to cover
            num_questions: Number of questions to generate
            
        Returns:
            Dictionary with quiz questions and metadata
        """
        logger.info(f"Generating quiz on topics: {topics}")
        
        # This would call the QuizAgent
        quiz = {
            'id': f"quiz_{datetime.now().strftime('%Y%m%d%H%M%S')}",
            'topics': topics,
            'questions': [],
            'total_points': num_questions * 10
        }
        
        return quiz
    
    def track_progress(self, user_id: str, topic: str, score: int) -> Dict:
        """
        Track student learning progress.
        
        Args:
            user_id: Student identifier
            topic: Topic studied
            score: Quiz or assessment score
            
        Returns:
            Updated progress information
        """
        logger.info(f"Tracking progress for {user_id}: {topic} = {score}%")
        
        # This would use ProgressTracker tool
        progress = {
            'user_id': user_id,
            'topic': topic,
            'score': score,
            'timestamp': datetime.now().isoformat(),
            'improvement': "+15%"  # Would be calculated
        }
        
        return progress
    
    def chat(self, message: str, session_id: Optional[str] = None) -> str:
        """
        Interactive chat interface with the education assistant.
        
        Args:
            message: User message
            session_id: Optional session ID for conversation continuity
            
        Returns:
            Agent response
        """
        if not session_id:
            session_id = f"session_{datetime.now().strftime('%Y%m%d%H%M%S')}"
            self.sessions[session_id] = []
        
        self.sessions[session_id].append({
            'role': 'user',
            'content': message,
            'timestamp': datetime.now().isoformat()
        })
        
        logger.info(f"Processing chat message in session {session_id}")
        
        # This would route to appropriate agent based on intent
        response = f"Processing your request: {message}"
        
        self.sessions[session_id].append({
            'role': 'assistant',
            'content': response,
            'timestamp': datetime.now().isoformat()
        })
        
        return response


def main():
    """
    Main function to run the Education Assistant Agent.
    """
    print("=" * 60)
    print("  AI Education Assistant Agent")
    print("  C++ & Algorithms Exam Preparation")
    print("  Agents Intensive Capstone Project")
    print("=" * 60)
    print()
    
    try:
        # Initialize agent
        agent = EducationAssistantAgent()
        
        # Demo: Explain a concept
        print("\n[Demo] Explaining QuickSort...")
        explanation = agent.explain_concept("quicksort", difficulty="medium")
        print(explanation)
        
        # Demo: Generate quiz
        print("\n[Demo] Generating quiz...")
        quiz = agent.generate_quiz(["sorting", "heaps"], num_questions=3)
        print(f"Quiz ID: {quiz['id']}")
        print(f"Topics: {', '.join(quiz['topics'])}")
        
        # Demo: Track progress
        print("\n[Demo] Tracking progress...")
        progress = agent.track_progress("student123", "sorting", score=85)
        print(f"Progress: {progress['topic']} - {progress['score']}%")
        
        # Interactive mode
        print("\n" + "="*60)
        print("Interactive Mode (type 'quit' to exit)")
        print("="*60)
        
        session_id = None
        while True:
            try:
                user_input = input("\nYou: ").strip()
                if user_input.lower() in ['quit', 'exit', 'q']:
                    print("Goodbye! Happy studying!")
                    break
                
                if user_input:
                    response = agent.chat(user_input, session_id)
                    print(f"\nAssistant: {response}")
            except KeyboardInterrupt:
                print("\n\nGoodbye! Happy studying!")
                break
    
    except Exception as e:
        logger.error(f"Error running agent: {e}")
        print(f"\nError: {e}")
        print("Make sure GOOGLE_API_KEY is set in your environment.")


if __name__ == "__main__":
    main()
